#!/bin/zsh

echo "npm run format"
docker-compose exec -T app npm run format

if [ $? -ne 0 ]; then
  echo "Lint エラーがあります。修正してからコミットしてください。"
  exit 1
fi

git add .
exit 0

echo "All jobs run successed.";