import { GeistSans } from "geist/font/sans";
import { dir } from "i18next";
import { Noto_Sans_JP } from "next/font/google";

import type { Metadata } from "next";
import "../globals.css";

const NotoSansJP = Noto_Sans_JP({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
  variable: "--noto-sans-jp",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: string };
}>) {
  return (
    <html lang={lang} dir={dir(lang)}>
      <body
        className={`${GeistSans.className} ${NotoSansJP.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
